// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC037PK8SGzapeexw83RrLktyoaKzSd4rc',
    appId: '1:621276435778:web:6d7ad22374838b42ada4db',
    messagingSenderId: '621276435778',
    projectId: 'fluter-77065',
    authDomain: 'fluter-77065.firebaseapp.com',
    storageBucket: 'fluter-77065.appspot.com',
    measurementId: 'G-K002L9XCGY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8EgDeQqTueYalwxnLFhoegR84of-IJK0',
    appId: '1:621276435778:android:55838afd84017cb0ada4db',
    messagingSenderId: '621276435778',
    projectId: 'fluter-77065',
    storageBucket: 'fluter-77065.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMVjJXA69bQa8gDUZFkFlPP_orQWD_zUQ',
    appId: '1:621276435778:ios:28113e67556794c3ada4db',
    messagingSenderId: '621276435778',
    projectId: 'fluter-77065',
    storageBucket: 'fluter-77065.appspot.com',
    iosClientId: '621276435778-rdgial9vkjenlmsel3o7rtpcn31gb09s.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMVjJXA69bQa8gDUZFkFlPP_orQWD_zUQ',
    appId: '1:621276435778:ios:28113e67556794c3ada4db',
    messagingSenderId: '621276435778',
    projectId: 'fluter-77065',
    storageBucket: 'fluter-77065.appspot.com',
    iosClientId: '621276435778-rdgial9vkjenlmsel3o7rtpcn31gb09s.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectFlutterApp',
  );
}
